name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: win32
          cos: "Win32 -DSUSIE_PLUGIN=on"
          ext: spi
        - os: win64
          cos: "x64 -DFISHELLEXT=on"
          ext: dll
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/setup-nasm@v1
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.os }}
    - name: Compile
      run: |
        cmake build -G "Visual Studio 17 2022" -A ${{ matrix.cos }}
        cmake --build . --config Release
        move Release\*.dll .
        move plugin\Release\*.${{ matrix.ext }} .
        7z a ${{ matrix.os }}.7z *.dll *.spi
        md include
        md lib
        move src\FreeImage.h include
        move Release\*.lib lib
        7z a ${{ matrix.os }}-dev.7z include lib
    - name: Compile LuaJIT
      shell: cmd
      run: |
        curl -O http://luajit.org/download/LuaJIT-2.1.0-beta3.zip
        curl -OL https://github.com/nyfair/fi-luajit/archive/master.zip
        7z x *.zip
        cd LuaJIT-2.1.0-beta3\src
        msvcbuild amalg
    - name: Make Lua Binding
      run: |
        cd LuaJIT-2.1.0-beta3\src
        md lua
        move ..\..\fi-luajit-master\*.lua lua
        move ..\..\fi-luajit-master\test\* .
        7z a ..\..\${{ matrix.os }}-luajit-bind.7z *.exe *.dll *.lua lua
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.os }}*.7z
        tag: latest
        overwrite: true
        file_glob: true
